//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressSplitForExcel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SenderAddressInfo
    {
        public long ID { get; set; }
        public string Sender { get; set; }
        public string Mobile { get; set; }
        public string Provience { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Address { get; set; }
    }
}
